#!/bin/bash
# run script for PicturePi
# place in /opt/picturepi/bin

# check if PicturePi is already running and kill it
PID=$(ps -ef | grep picturepi.jar | grep -v grep | awk '{print $2}')
if [ -n "$PID" ]; then
  kill $PID
fi

# hide mouse cursor (unclutter must be installed  separately)
/usr/bin/unclutter -display :0 -idle 0

#!/bin/bash
export DISPLAY=:0
/usr/bin/java  -classpath '/opt/picturepi/bin/picturepi.jar' picturepi/PicturePi &
